{% set name = "neobolt" %}
{% set version = "1.7.17" %}
{% set sha256 = "1d0d5efce7221fc4f0ffc4a315bc5272708be5aa2aef5434269e800372d8db89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pytz
    - neotime

test:
  imports:
    - neobolt
    - neobolt.direct
    - neobolt.exceptions
    - neobolt.routing

about:
  home: http://neobolt.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Neo4j Bolt connector for Python
  description: |
    Neobolt is a Bolt connector library for Python. It is generally intended for use by a higher level driver.
  doc_url: http://neobolt.readthedocs.io/en/latest/
  dev_url: https://github.com/technige/neobolt

extra:
  recipe-maintainers:
    - thebestnom
